package dependencies

object Versions {
    val gradle = "3.5.3"
    val compilesdk = 29
    val minsdk = 21
    val targetsdk = 29
    val kotlin = "1.3.61"
    val ktx = "1.2.0"
    val dagger = "2.25.4"
    val nav_components = "2.3.0-alpha06"
    val material_dialogs = "3.2.1"
    val room = "2.1.0"
    val appcompat = "1.1.0-rc01"
    val constraintlayout = "1.1.3"
    val material_design = "1.1.0"
    val play_core = "1.7.1"
    val play_services = "4.3.3"
    val leak_canary = "2.0-alpha-3"
    val swipe_refresh_layout = "1.1.0-alpha03"
    val firebase_firestore = "21.4.2"
    val firebase_analytics = "17.4.0"
    val firebase_crashlytics = "2.10.1"
    val firebase_auth = "19.3.0"
    val espresso_core = "3.1.1"
    val espresso_idling_resource = "3.2.0"
    val mockk_version = "1.9.2"
    val test_runner = "1.2.0"
    val test_core = "1.2.0"
    val coroutines_version = "1.3.0"
    val coroutines_play_services = "1.3.2"
    val lifecycle_version = "2.2.0-alpha03"
    val retrofit2_version = "2.6.0"
    val markdown_processor = "0.1.3"
    val junit_jupiter_version = "5.6.0"
    val junit_4_version = "4.12"
    val fragment_version = "1.2.0"
    val androidx_test_ext = "1.1.1"
    val fabric_version = "1.31.2"
}